spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:

    # 24 hours in milliseconds
  cors:
    allowed-origins: http://localhost:5173
  aws:
    access-key: your_aws_access_key
    secret-key: your_aws_secret_key
    region: us-east-1
    s3:
      bucket: your-bucket-name